Kafka:
  server: "localhost"
  port: "9092"
  model_topic: "gala_anteater_hybrid_model"
  model_group_id: "gala_anteater_1"
  meta_topic: "gala_gopher_metadata"
  meta_group_id: "gala_anteater_1"
  meta_entity_name: "sli"

Prometheus:
  server: "localhost"
  port: "9090"
  steps: 5

HybridModel:
  name: "vae"
  conf_folder: "config"
  model_folder: "models"
  latest_model_folder: "latest_models"
  retrain: false
  keep_model: true
  threshold: 0.5

SLIModel:
  RTT:
    name: "gala_gopher_sli_rtt_nsec"
    threshold: 200000

  TPS:
    name: "gala_gopher_sli_tps"
    threshold: 1.5

SCHEDULE:
  duration: 1
