Global:
    data_source: "prometheus"

Kafka:
  server: "localhost"
  port: "9092"
  model_topic: "gala_anteater_hybrid_model"
  meta_topic: "gala_gopher_metadata"

Prometheus:
  server: "localhost"
  port: "9090"
  steps: 5

Aom:
  base_url: ""
  project_id: ""
  auth_type: "token"
  auth_info:
    iam_server: ""
    iam_domain: ""
    iam_user_name: ""
    iam_password: ""
    ssl_verify: 0

Schedule:
  duration: 1
